name: eslint check
on: [push]
jobs:
  run and lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo Installing dependecies
      - run: make install
      - run: echo checking by eslint
      - run: make lint
