name: eslint-check
on: 
  push:
    branches:
      - master 
 
jobs:
  run-and-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Eslint checking
        run: make install
      - run: echo checking by eslint
      - run: make lint
